### ISSUE TITLE
Fails to initialize on node v12 (LTS)

### ISSUE THREAD

**Issue by karolyi** [sublimelsp/LSP-eslint#13]
Hi,
after installing, I get the following error in the console:
```
lsp-eslint: ESLint server running in node v12.14.0
lsp-eslint: Registering request handler for workspace/didChangeConfiguration failed.
lsp-eslint: (node:74725) UnhandledPromiseRejectionWarning: Error: client/registerCapability
lsp-eslint: Registering request handler for workspace/didChangeWorkspaceFolders failed.
lsp-eslint: at handleResponse (/Users/karolyi/Library/Application Support/Sublime Text 3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:447:48)
lsp-eslint: at processMessageQueue (/Users/karolyi/Library/Application Support/Sublime Text 3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:274:17)
lsp-eslint: at Immediate.<anonymous> (/Users/karolyi/Library/Application Support/Sublime Text 3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:258:13)
lsp-eslint: at processImmediate (internal/timers.js:439:21)
lsp-eslint: (node:74725) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
lsp-eslint: (node:74725) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
lsp-eslint: (node:74725) UnhandledPromiseRejectionWarning: Error: client/registerCapability
lsp-eslint: at handleResponse (/Users/karolyi/Library/Application Support/Sublime Text 3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:447:48)
lsp-eslint: at processMessageQueue (/Users/karolyi/Library/Application Support/Sublime Text 3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:274:17)
lsp-eslint: at Immediate.<anonymous> (/Users/karolyi/Library/Application Support/Sublime Text 3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:258:13)
lsp-eslint: at processImmediate (internal/timers.js:439:21)
lsp-eslint: (node:74725) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

and then eslint is not working. Please investigate.

**Comment by rchl** [comment]
This error should not prevent server from working. There must be a different reason for it not working.
Are there any more logs related to lsp-eslint in LSP console?

**Comment by karolyi** [comment]
Hey,

I don't see things being marked as syntactically invalid. Here are the logs after those lines:
```
:: --> lsp-eslint initialize(1): {'rootPath': '/Users/karolyi/Work/project', 'capabilities': {'workspace': {'executeCommand': {}, 'workspaceFolders': True, 'applyEdit': True, 'didChangeConfiguration': {}, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'configuration': True}, 'textDocument': {'references': {}, 'colorProvider': {}, 'formatting': {}, 'completion': {'completionItem': {'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}, 'synchronization': {'willSaveWaitUntil': True, 'willSave': True, 'didSave': True}, 'documentHighlight': {}, 'rename': {}, 'definition': {'linkSupport': True}, 'publishDiagnostics': {'relatedInformation': True}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'implementation': {'linkSupport': True}, 'typeDefinition': {'linkSupport': True}, 'declaration': {'linkSupport': True}, 'signatureHelp': {'signatureInformation': {'documentationFormat': ['markdown', 'plaintext'], 'parameterInformation': {'labelOffsetSupport': True}}}, 'hover': {'contentFormat': ['markdown', 'plaintext']}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}, 'rangeFormatting': {}}}, 'rootUri': 'file:///Users/karolyi/Work/project', 'workspaceFolders': [{'name': 'ticketshop', 'uri': 'file:///Users/karolyi/Work/project'}], 'processId': 76037}
:: <<< lsp-eslint 1: {'capabilities': {'codeActionProvider': True, 'executeCommandProvider': {'commands': ['eslint.applySingleFix', 'eslint.applySameFixes', 'eslint.applyAllFixes', 'eslint.applyAutoFix', 'eslint.applyDisableLine', 'eslint.applyDisableFile', 'eslint.openRuleDoc']}, 'textDocumentSync': {'save': {'includeText': False}, 'change': 1, 'willSaveWaitUntil': True, 'openClose': True}}}
::  -> lsp-eslint initialized: {}
::  -> lsp-eslint textDocument/didOpen
:: <-- lsp-eslint client/registerCapability(0): {'registrations': [{'id': '95ab6514-7f0a-4b8a-a16d-78166fd695c9', 'method': 'workspace/didChangeConfiguration', 'registerOptions': {}}]}
:: ~~> lsp-eslint 0: {'message': 'client/registerCapability', 'code': -32601}
:: <-- lsp-eslint client/registerCapability(1): {'registrations': [{'id': 'b2e8f564-4023-440a-b540-e79d3426a793', 'method': 'workspace/didChangeWorkspaceFolders', 'registerOptions': {}}]}
:: ~~> lsp-eslint 1: {'message': 'client/registerCapability', 'code': -32601}
:: <-- lsp-eslint workspace/configuration(2): {'items': [{'section': '', 'scopeUri': 'file:///Users/karolyi/Work/project/frontend/src/js/test.js'}]}
:: >>> lsp-eslint 2: [{}]
::  -> lsp-eslint textDocument/didOpen
lsp-eslint: ESLint library loaded from: /Users/karolyi/Work/project/node_modules/eslint/lib/api.js
::  -> lsp-eslint textDocument/didChange
::  -> lsp-eslint textDocument/didChange
:: ==> lsp-eslint textDocument/willSaveWaitUntil(2): {'reason': 1, 'textDocument': {'uri': 'file:///Users/karolyi/Work/project/frontend/src/js/test.js'}}
:: <<< lsp-eslint 2: []
::  -> lsp-eslint textDocument/didSave: {'textDocument': {'uri': 'file:///Users/karolyi/Work/project/frontend/src/js/test.js'}}
```
do you have any clues on this?

**Comment by rchl** [comment]
There is something wrong with LSP-eslint settings. Open `Preferences: LSP-eslint Settings` from Command Palette or main menu and check for anything that is wrong there.
Post your settings if you can't figure it out yourself.
I'm assuming you are using latest version of LSP-eslint (0.0.4).

**Comment by karolyi** [comment]
Hey,

I had to adjust the LSP config a bit since I use an updated JS Syntax highlighting. Here's my modified config, I think it should be okay:
```json
// Settings in here override those in "LSP-eslint/LSP-eslint.sublime-settings",

{
    "client": {
        "enabled": true,
    	"languages": [
    		{
    			"languageId": "javascript",
    			"scopes": ["source.js", "text.html.vue"],
    			"syntaxes": ["Javascript", "JavaScript Next", "Packages/JavaScriptNext - ES6 Syntax/JavaScriptNext.tmLanguage"],
    		}
    	]
    }
}
```

do you recognize anything suspicious?

**Comment by rchl** [comment]
If you look at default settings, you'll see that it uses `eslint` as `languageId`. Try changing to that.

**Comment by rchl** [comment]
No, sorry, that's not the main issue. The main issue is that `workspace/configure` response doesn't include default settings.
When you open eslint preferences with split view, do you see proper configuration on the left?

**Comment by karolyi** [comment]
Tried changing to `eslint`, no change.

Yes, the split panel's left side has this as the default config:
```json
{
	"client" : {
		"enabled": true,
		"languages": [
			{
				"languageId": "eslint",
				"scopes": ["source.js", "text.html.vue"],
				"syntaxes": [
					"Packages/Vue Syntax Highlight/Vue Component.sublime-syntax",
					"Packages/JavaScript/JavaScript.sublime-syntax",
					"Packages/User/JS Custom/Syntaxes/React.sublime-syntax",
					"Packages/JavaScript/JavaScript.sublime-syntax",
					"Packages/Babel/JavaScript (Babel).sublime-syntax"
				]
			}
		],
		"initializationOptions": {},
		"settings": {
			"validate": true,
			"packageManager": "npm",
			"autoFix": true,
			"autoFixOnSave": true,
			"options": {},
			"run": "onType",
			"nodePath": null,
			"quiet": false,
			"workspaceFolder": null,
			"codeAction": {
				"disableRuleComment": {
					"enable": true,
					"location": "separateLine"
				},
				"showDocumentation": {
					"enable": true
				}
			}
		}
	}
}
```

I override only the `languages` key under `client`, shouldn't it merge with the default config when building a configuration?

**Comment by rchl** [comment]
Yes, it should merge and it does for me.
I'm not sure I have an idea how to debug it further but it would be more efficient if we could talk about it on Discord (https://github.com/sublimelsp/LSP#chat)

**Comment by predragnikolic** [comment]
>  shouldn't it merge with the default config when building a configuration

It should but it doesn't work like that, unfortunately.

for example if we have a default setting like this:
```
// default settings
{
	"client" : {
		"enabled": true,
		"languages": [
			{
				"languageId": "elm",
				"scopes": ["source.elm"],
				"syntaxes": ["Packages/Elm Syntax Highlighting/src/elm.sublime-syntax"]
			}
		],
		"initializationOptions": {
			"elmAnalyseTrigger": "change"
		},
		"settings": {}
	}
}
```

And a user setting like this:
```
{
    "client": {
        
    } 
}
```
when they get merged the end result is. Which nobody expected. 

```
{
    "client": {
        
    } 
}
```

That is the reason why I liked the new flatten structure settings file we introduced lately.
For example, the new settings file look like this:
```
// default settings
{
	"languages": [
		{
			"languageId": "php",
			"scopes": ["source.php"],
			"syntaxes": [
				"Packages/PHP/PHP.sublime-syntax",
			],
		},
	],
	"initializationOptions": {
		"clearCache": false,
		// "storagePath": "/tmp/intelephense",
		// "globalStoragePath": "/tmp/intelephense",
		// "licenceKey": "${packages}/User/intelephense-license.txt",
	},
	// @see configuration in https://github.com/bmewburn/vscode-intelephense/blob/master/package.json
	"settings": {
		// as an example
		"debug": {
			"enable": false,
		},
	},
}
```
note that there is no "client" entry key.

```
// user settings
{
    "initializationOptions": {},
    "settings": {}
}
```

end results would be:
```

{
	"languages": [
		{
			"languageId": "php",
			"scopes": ["source.php"],
			"syntaxes": [
				"Packages/PHP/PHP.sublime-syntax",
			],
		},
	],
	"initializationOptions": {}, //  this has change
	"settings": {},  // this has change
}
```
