### ISSUE TITLE
It doesn't seem to auto-install correctly

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-eslint#19]
I'm trying to run eslint.

I'm auto-installing the server. But after restarting ST it crashes immediately. These are my logs:

```
:: --> lsp-eslint initialize(1): {'clientInfo': {'name': 'Sublime Text LSP'}, 'initializationOptions': {}, 'processId': 19826, 'rootUri': 'file:///home/raoul/dev/temp/nuxt-i18n', 'capabilities': {'workspace': {'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'applyEdit': True, 'configuration': True, 'executeCommand': {}, 'workspaceFolders': True, 'didChangeConfiguration': {}}, 'textDocument': {'hover': {'contentFormat': ['markdown', 'plaintext']}, 'formatting': {}, 'definition': {'linkSupport': True}, 'rename': {}, 'synchronization': {'didSave': True, 'willSaveWaitUntil': True, 'willSave': True}, 'references': {}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'completion': {'completionItem': {'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}, 'publishDiagnostics': {'relatedInformation': True}, 'colorProvider': {}, 'rangeFormatting': {}, 'signatureHelp': {'signatureInformation': {'parameterInformation': {'labelOffsetSupport': True}, 'documentationFormat': ['markdown', 'plaintext']}}, 'typeDefinition': {'linkSupport': True}, 'documentHighlight': {}, 'implementation': {'linkSupport': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}, 'declaration': {'linkSupport': True}}}, 'workspaceFolders': [{'uri': 'file:///home/raoul/dev/temp/nuxt-i18n', 'name': 'nuxt-i18n'}], 'rootPath': '/home/raoul/dev/temp/nuxt-i18n'}
lsp-eslint: throw err;
lsp-eslint: internal/modules/cjs/loader.js:800
lsp-eslint: throw err;
```

I should note that I'm installing eslint while a JS file is open. So LSP is trying to start the server but it is still installing. I'm not sure if this is related, but might be a clue.

**Comment by rchl** [comment]
> So LSP is trying to start the server but it is still installing.

It wouldn't start at this point thanks to this change a161c6a7d245ed1d108c55b8111cc891db2d3a38

Could you look inside `Cache/LSP-eslint` and check that `node_modules` directory exists and has a decent size? This is what I see:
![Screenshot 2020-04-13 at 19 17 59](https://user-images.githubusercontent.com/153197/79142287-90ce0a80-7dbb-11ea-8c9f-06f7942273ef.png)

**Comment by rwols** [comment]
It's 19MB here:

```
~/.c/s/C/L/vscode-eslint $ pwd
/home/raoul/.config/sublime-text-3/Cache/LSP-eslint/vscode-eslint
~/.c/s/C/L/vscode-eslint $ du -hs node_modules/
19M	node_modules/
```

Node version:

```
~/.c/s/C/L/vscode-eslint $ node --version
v12.13.1
```

I'm on Ubuntu 19.10 if that helps

**Comment by rwols** [comment]
Running eslint in the terminal I get this

```
~/.c/s/C/L/v/out $ node eslintServer.js
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'vscode-languageserver-textdocument'
Require stack:
- /home/raoul/.config/sublime-text-3/Cache/LSP-eslint/vscode-eslint/out/eslintServer.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/raoul/.config/sublime-text-3/Cache/LSP-eslint/vscode-eslint/out/eslintServer.js:8:46)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/raoul/.config/sublime-text-3/Cache/LSP-eslint/vscode-eslint/out/eslintServer.js'
  ]
}
```

**Comment by rchl** [comment]
I'll try on Ubuntu but do you have those directories in node_modules?
![Screenshot 2020-04-13 at 19 33 53](https://user-images.githubusercontent.com/153197/79143591-c96ee380-7dbd-11ea-8324-00fa0d3986b7.png)

**Comment by rwols** [comment]
> do you have those directories in node_modules?

No:

```
~/.c/s/C/L/vscode-eslint $ ls -lash node_modules/
total 40K
4,0K drwxr-xr-x 10 raoul raoul 4,0K apr 13 19:30  ./
4,0K drwxr-xr-x  4 raoul raoul 4,0K apr 13 19:30  ../
4,0K drwxr-xr-x  2 raoul raoul 4,0K apr 13 19:30  .bin/
4,0K drwxr-xr-x  3 raoul raoul 4,0K apr 13 19:30 '@types'/
4,0K drwxr-xr-x  4 raoul raoul 4,0K apr 13 19:30  vscode-jsonrpc/
4,0K drwxr-xr-x  5 raoul raoul 4,0K apr 13 19:30  vscode-languageserver/
4,0K drwxr-xr-x  3 raoul raoul 4,0K apr 13 19:30  vscode-languageserver-protocol/
4,0K drwxr-xr-x  3 raoul raoul 4,0K apr 13 19:30  vscode-languageserver-types/
4,0K drwxr-xr-x  4 raoul raoul 4,0K apr 13 19:30  vscode-textbuffer/
4,0K drwxr-xr-x  4 raoul raoul 4,0K apr 13 19:30  vscode-uri/
```

Grepping for that string gives me this, if it helps :)

```
~/.c/s/C/L/vscode-eslint $ grep -rni 'vscode-languageserver-textdocument' *
out/eslintServer.js:8:const vscode_languageserver_textdocument_1 = require("vscode-languageserver-textdocument");
package-lock.json:41:		"vscode-languageserver-textdocument": {
package-lock.json:43:			"resolved": "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.0.tgz",
package.json:20:		"vscode-languageserver-textdocument": "1.0.0"
```

**Comment by rchl** [comment]
I've tried on ubuntu (same node version, ST3, LSP master) and it worked fine...

I wonder if the installation got interrupted somehow the first time it tried.
You could try re-installing LSP-eslint to see if that helps.

**Comment by rchl** [comment]
Actually, on Ubuntu I also don't have `vscode-languageserver-textdocument` but it works. Let me dig deeper.

**Comment by rchl** [comment]
OK, so actually latest released version doesn't use `vscode-languageserver-textdocument`. That is only used on the master branch of `LSP-eslint` (not released yet). So there seems to be some mismatch - node modules from old version and the main vscode-eslint script from latest version.

**Comment by rchl** [comment]
Not sure what to make out of it but probably it was some local issue related to switching branches. Should we close it?
