### ISSUE TITLE
Exited with status code 1

### ISSUE THREAD

**Issue by privatmamtora** [sublimelsp/LSP-eslint#50]
# Troubleshooting: LSP-eslint
## Version
 - LSP: 1.13.0
 - Sublime Text: 4121
## Server Test Run
 - exit code: 1
 - output
```
C:\Users\***\AppData\Local\Sublime Text 3\Package Storage\LSP-eslint\12.14.1\language-server\out\eslintServer.js:242
        return ruleId2Meta.get(ruleId)?.docs?.url;
                                       ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
"C:\Program Files\nodejs\node.EXE" "C:\Users\***\AppData\Local\Sublime Text 3\Package Storage\LSP-eslint\12.14.1\language-server\out\eslintServer.js" --stdio
```
 - selector
```
(source.jsx | source.js.jsx | source.js.react)|(source.js)|(source.tsx | source.ts.react)|(source.ts)|(text.html.vue)|(text.html.basic)
```
 - priority_selector
```
(source.javascriptreact)|(source.javascript)|(source.typescriptreact)|(source.typescript)|(source.vue)|(source.html)
```
 - init_options
```json
{}
```
 - settings
```json
{
  "codeAction": {
    "disableRuleComment": {
      "enable": true, 
      "location": "separateLine"
    }, 
    "showDocumentation": {
      "enable": true
    }
  }, 
  "codeActionOnSave": {
    "enable": true, 
    "mode": "all"
  }, 
  "format": false, 
  "nodePath": null, 
  "onIgnoredFiles": "off", 
  "options": {}, 
  "packageManager": "npm", 
  "probe": [
    "javascript", 
    "javascriptreact", 
    "typescript", 
    "typescriptreact", 
    "html", 
    "vue", 
    "markdown"
  ], 
  "quiet": false, 
  "rulesCustomizations": [], 
  "run": "onType", 
  "useESLintClass": false, 
  "validate": [
    "javascript", 
    "javascriptreact"
  ]
}
```
 - env
```json
{
  "PATH": "C:\\Program Files\\nodejs;C:\\Program Files\\nodejs;"
}
```

## Active view
 - File name
```
C:\Users\***\Experimental\IniToJson\index.js
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/JavaScript/JavaScript.sublime-syntax"
}
```
 - base scope
```
source.js
```

## Project / Workspace
 - folders
```json
[
  "C:\\Users\\***\\Experimental\\IniToJson"
]
```
 - is project: False

## LSP configuration

<not found>

**Comment by rchl** [comment]
Means your node version is too old. You need at least v14.

**Comment by rchl** [comment]
I've also updated the code and released new version so this will be communicated more clearly to the user.

**Comment by Mar-Ser** [comment]
According to https://nodejs.org/en/about/releases/ Nodejs v12 is still supported.
I believe it will be better to rebuild server with proper `--target`.

**Comment by rchl** [comment]
We could but why fight against what the server author chooses to use?

The current stable version of Node is v16 and v12 is in maintenance mode. Why should we bother with supporting it?

**Comment by Mar-Ser** [comment]
Because it is still in use by some projects?
I really want to use the latest node version, but for our project migration to it is a huge task...

**Comment by rchl** [comment]
Then maybe open `Preferences: LSP Utils Settings` from the Command Palette and set

```
    "nodejs_runtime": ["local"],
```

Then the LSP will use node version maintained by lsp_utils rather than your globally installed node version.

**Comment by Mar-Ser** [comment]
I hope it will not break anything. Checked briefly and it works for me. Thank you!
